baseURL = 'https://shaqmo.github.io/blog/'
languageCode = 'en-us'
title = 'My Blog'
theme = 'PaperMod'

[params]
  homeInfoParams = { Title = "Hi, I'm Shakeel", Content = "Welcome to my blog." }

[[menus.main]]
  name = 'About'
  url = '/about/'
  weight = 10

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
